version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: fiu-scheduler-db
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler -d scheduler"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    container_name: fiu-scheduler-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scheduler
      SPRING_DATASOURCE_USERNAME: scheduler
      SPRING_DATASOURCE_PASSWORD: scheduler
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data: 